import { useState } from "react";
import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { Bell, Bike, BookOpen, Boxes, CalendarCheck, ChevronDown, CircleDollarSign, ClipboardList, FileText, Gauge, Landmark, Menu, ReceiptIndianRupee, Search, Settings, ShieldCheck, UserRound, Users, WalletCards } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { notifications, searchRecords } from "@/lib/mock-service";
import { cn } from "@/lib/utils";

const items = [
  ["Dashboard", "/dashboard", Gauge], ["Customers", "/customers", Users], ["Enquiries", "/enquiries", ClipboardList], ["Proforma Invoices", "/proforma", FileText], ["Bookings", "/bookings", BookOpen], ["Vehicle Inventory", "/inventory", Boxes], ["Finance", "/finance", Landmark], ["Insurance", "/insurance", ShieldCheck], ["Registration", "/registration", Bike], ["Deliveries", "/deliveries", CalendarCheck], ["Accounts", "/accounts", WalletCards], ["Reports", "/reports", ReceiptIndianRupee], ["Settings", "/settings", Settings],
] as const;

function AppSidebar() {
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  const { state } = useSidebar();
  return <Sidebar collapsible="icon" className="border-r border-sidebar-border/70 bg-sidebar/80 backdrop-blur-2xl"><SidebarHeader className="h-20 justify-center border-b border-sidebar-border/60 px-4"><Link to="/dashboard" className="flex items-center gap-3 overflow-hidden"><span className="brand-gradient grid size-10 shrink-0 place-items-center rounded-xl text-primary-foreground shadow-glow"><Bike className="size-5"/></span>{state === "expanded" && <span className="min-w-0"><strong className="block truncate font-display text-sm font-semibold">SRIVAARI AUTOMOBILES</strong><small className="text-xs text-muted-foreground">Automobiles & Finance</small></span>}</Link></SidebarHeader><SidebarContent><SidebarGroup className="px-2 py-4"><SidebarGroupContent><SidebarMenu className="gap-1">{items.map(([label, to, Icon]) => <SidebarMenuItem key={to}><SidebarMenuButton asChild isActive={pathname === to || (to !== "/dashboard" && pathname.startsWith(to))} tooltip={label} className="h-10 rounded-xl transition-all duration-200 hover:bg-primary-soft hover:text-primary data-[active=true]:brand-gradient data-[active=true]:text-primary-foreground data-[active=true]:shadow-soft"><Link to={to}><Icon/><span>{label}</span></Link></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="border-t border-sidebar-border/60 p-3"><div className="flex items-center gap-3 overflow-hidden rounded-xl border border-transparent p-2 transition-colors hover:border-border hover:bg-card/60"><Avatar className="size-9"><AvatarFallback className="bg-primary-soft text-primary">SK</AvatarFallback></Avatar>{state === "expanded" && <div className="min-w-0"><p className="truncate text-sm font-semibold">S. Kannan</p><p className="text-xs text-muted-foreground">Owner / Admin</p></div>}</div></SidebarFooter></Sidebar>;
}

function SearchDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const navigate = useNavigate();
  return <CommandDialog open={open} onOpenChange={onOpenChange}><CommandInput placeholder="Search customer, phone, booking, chassis, engine..."/><CommandList><CommandEmpty>No showroom records found.</CommandEmpty>{["CUSTOMER", "BOOKING", "VEHICLE", "FINANCE", "INSURANCE", "REGISTRATION"].map((group) => <CommandGroup key={group} heading={group}>{searchRecords.filter((record) => record.type === group).map((record) => <CommandItem key={record.id} value={`${record.title} ${record.subtitle} 9876543210`} onSelect={() => { onOpenChange(false); navigate({ to: record.href }); }}><Search/><div><p className="font-semibold">{record.title}</p><p className="text-xs text-muted-foreground">{record.subtitle}</p></div></CommandItem>)}</CommandGroup>)}</CommandList></CommandDialog>;
}

export function AppShell({ children }: { children: React.ReactNode }) {
  const [searchOpen, setSearchOpen] = useState(false);
  return <SidebarProvider><AppSidebar/><main className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-20 items-center gap-3 border-b border-border/60 bg-background/68 px-4 backdrop-blur-2xl lg:px-8"><SidebarTrigger/><button onClick={() => setSearchOpen(true)} className="mx-auto flex h-11 w-full max-w-2xl items-center gap-3 rounded-xl border border-border/80 bg-card/72 px-4 text-left text-sm text-muted-foreground shadow-xs backdrop-blur-md transition-all duration-200 hover:border-primary/30 hover:bg-card hover:shadow-soft"><Search className="size-4 text-primary"/><span className="truncate">Search customer, phone, booking, chassis, engine...</span><kbd className="ml-auto hidden rounded-md border border-border bg-muted/75 px-2 py-1 text-[10px] sm:block">⌘ K</kbd></button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="relative"><Bell/><span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-destructive ring-2 ring-background"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-80 rounded-2xl border-border/70 bg-popover/92 p-2 shadow-float backdrop-blur-xl"><DropdownMenuLabel className="flex items-center justify-between">Notifications <span className="text-xs text-primary">4 new</span></DropdownMenuLabel><DropdownMenuSeparator/>{notifications.map((item) => <DropdownMenuItem key={item.id} asChild className="items-start rounded-xl p-3"><Link to={item.href}><span className={cn("mt-1 size-2 shrink-0 rounded-full", item.tone === "danger" && "bg-destructive", item.tone === "warning" && "bg-warning", item.tone === "success" && "bg-success")}/><span><strong className="block text-xs">{item.title}</strong><small className="text-muted-foreground">{item.detail}</small></span></Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="hidden gap-2 px-2 sm:flex"><Avatar className="size-8"><AvatarFallback className="brand-gradient text-primary-foreground">SK</AvatarFallback></Avatar><ChevronDown/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="rounded-xl border-border/70 bg-popover/92 shadow-float backdrop-blur-xl"><DropdownMenuLabel>S. Kannan</DropdownMenuLabel><DropdownMenuItem><UserRound/> Profile</DropdownMenuItem><DropdownMenuItem><Settings/> Settings</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><div className="mx-auto max-w-[1600px] p-4 lg:p-8">{children}</div></main><SearchDialog open={searchOpen} onOpenChange={setSearchOpen}/><Toaster richColors position="top-right"/></SidebarProvider>;
}