import { lazy, Suspense, useMemo, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Bike, CalendarCheck, Check, ChevronRight, CircleDollarSign, ClipboardCheck, Clock3, Download, FileSpreadsheet, FileText, IndianRupee, Landmark, Plus, Printer, Search, Settings, ShieldCheck, TrendingUp, Pencil, Upload, UserPlus, Users, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { customers, records, vehicles } from "@/lib/mock-service";
import { formatCurrency } from "@/lib/domain";
import { EditLink, GlassCard, JourneyStepper, KpiCard, ModernTable, PageHeader, StatusBadge } from "@/components/shared";

function FilterPills({ options, active, onChange }: { options: string[]; active: string; onChange: (next: string) => void }) {
  return <div className="flex gap-2 overflow-x-auto pb-1">{options.map((item) => <Button key={item} variant={active === item ? "default" : "outline"} size="sm" onClick={() => onChange(item)}>{item}</Button>)}</div>;
}

export const pageFilters = {
  enquiries: ["All", "Open", "Follow-up Due", "Converted", "Lost"],
  proforma: ["All", "Draft", "Sent", "Accepted", "Expired"],
  bookings: ["All", "Booked", "Finance Pending", "Insurance Pending", "Registration Pending", "Ready for Delivery", "Delivered"],
  finance: ["All", "Submitted", "Under Review", "Approved", "Rejected", "Disbursed"],
  refinance: ["All", "Documents Pending", "Submitted", "Approved", "Rejected", "Disbursed"],
  insurance: ["All", "Requested", "Quote Received", "Policy Issued", "Expired"],
  registration: ["All", "Documents Pending", "Submitted", "Processing", "Number Allotted", "Completed"],
  deliveries: ["All", "Scheduled", "Ready", "Blocked", "Delivered"],
  customers: ["All", "Enquiry", "Booking", "Finance", "Registration", "Delivered"],
  inventory: ["All", "Available", "Reserved", "Booked", "In Transit", "Requirement", "Delivered"],
} as const;

const AccountsChart = lazy(() => import("@/components/accounts-chart"));

export function DashboardPage() {
  const pipeline = [["Enquiry", 18, "/enquiries"], ["Proforma", 14, "/proforma"], ["Booking", 12, "/bookings"], ["Payment", 9, "/bookings"], ["Finance", 5, "/finance"], ["Insurance", 7, "/insurance"], ["Registration", 9, "/registration"], ["Delivery", 4, "/deliveries"]] as const;
  return <div className="space-y-7"><PageHeader eyebrow="Saturday, 12 September" title="Good morning, Kannan" description="Here's what's happening at SRIVAARI AUTOMOBILES today." actions={<Button asChild><Link to="/bookings/new"><Plus/> New Booking</Link></Button>}/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><KpiCard label="Today's Bookings" value="12" trend="+18%" icon={<ClipboardCheck/>}/><KpiCard label="Pending Finance" value="5" trend="2 urgent" icon={<Landmark/>}/><KpiCard label="Available Vehicles" value="38" trend="+6 this week" icon={<Bike/>}/><KpiCard label="Insurance Pending" value="7" trend="3 today" icon={<ShieldCheck/>}/><KpiCard label="Registration Pending" value="9" trend="4 processing" icon={<FileText/>}/><KpiCard label="Deliveries Today" value="4" trend="On schedule" icon={<CalendarCheck/>}/></section>
  <GlassCard className="p-5 lg:p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-display text-lg font-bold">Customer pipeline</h2><p className="text-sm text-muted-foreground">Live movement from enquiry to delivery</p></div><span className="text-xs font-semibold text-success">58 active journeys</span></div><div className="grid gap-2 sm:grid-cols-4 xl:grid-cols-8">{pipeline.map(([label, count, to], index) => <Link key={label} to={to} className="group relative rounded-xl border border-border/70 bg-background/60 p-4 transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-soft"><span className="text-xs text-muted-foreground">0{index + 1}</span><strong className="mt-3 block text-2xl">{count}</strong><span className="text-xs font-semibold">{label}</span>{index < 7 && <ChevronRight className="absolute -right-2 top-1/2 z-10 hidden size-4 -translate-y-1/2 text-primary xl:block"/>}</Link>)}</div></GlassCard>
  <div className="grid gap-5 xl:grid-cols-[1fr_1.15fr]"><GlassCard className="p-5"><h2 className="font-display text-lg font-bold">Today's actions</h2><div className="mt-4 space-y-2">{[["3 Finance applications awaiting action", "Urgent", "/finance"], ["5 Insurance policies pending", "Today", "/insurance"], ["4 Registrations pending", "In progress", "/registration"], ["4 Deliveries scheduled today", "On track", "/deliveries"], ["7 Customer follow-ups due today", "Due", "/enquiries"]].map(([label, badge, to], index) => <Link key={label} to={to} className="flex items-center gap-3 rounded-xl p-3 transition hover:bg-primary-soft"><span className="grid size-9 place-items-center rounded-lg bg-muted text-primary"><Clock3 className="size-4"/></span><span className="min-w-0 flex-1 text-sm font-medium">{label}</span><StatusBadge status={badge} tone={index === 0 ? "danger" : index === 3 ? "success" : "warning"}/></Link>)}</div></GlassCard><GlassCard className="p-5"><h2 className="font-display text-lg font-bold">Recent activity</h2><div className="mt-4 space-y-4">{[["Payment received", "Ravi Kumar · BK-2026-00125", "9:42 AM"], ["Finance approved", "TVS Credit · FIN-2026-0087", "9:18 AM"], ["New enquiry", "Meena Lakshmi · TVS Jupiter", "8:56 AM"], ["Vehicle delivered", "Karthik Raj · Honda Shine", "Yesterday"]].map(([title, detail, time]) => <div key={title} className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-primary shadow-glow"/><div className="flex-1"><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">{detail}</p></div><time className="text-xs text-muted-foreground">{time}</time></div>)}</div></GlassCard></div></div>;
}

export function CustomersPage() { const [query, setQuery] = useState(""); const [stage, setStage] = useState("All"); const filtered = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.phone} ${customer.id}`.toLowerCase().includes(query.toLowerCase()) && (stage === "All" || customer.stage === stage)), [query, stage]); return <div className="space-y-6"><PageHeader title="Customers" description="Manage customer information and complete showroom history." actions={<Button asChild><Link to="/customers/new"><UserPlus/> New Customer</Link></Button>}/><FilterPills options={[...pageFilters.customers]} active={stage} onChange={setStage}/><GlassCard className="overflow-hidden"><div className="border-b border-border p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search name, phone, customer ID..."/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead className="bg-muted/60 text-left text-xs uppercase text-muted-foreground"><tr>{["Customer", "Customer ID", "Phone", "Location", "Current Stage", "Last Activity"].map((head) => <th key={head} className="px-5 py-3.5">{head}</th>)}</tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id} className="border-t border-border/60 hover:bg-primary-soft/40"><td className="px-5 py-4"><Link to="/customers/$id" params={{ id: customer.id }} className="font-semibold text-primary">{customer.name}</Link></td><td className="px-5 py-4 text-sm">{customer.id}</td><td className="px-5 py-4 text-sm">{customer.phone}</td><td className="px-5 py-4 text-sm text-muted-foreground">{customer.location}</td><td className="px-5 py-4"><StatusBadge status={customer.stage}/></td><td className="px-5 py-4 text-sm text-muted-foreground">{customer.lastActivity}</td></tr>)}</tbody></table></div></GlassCard></div>; }

export function CustomerDetailPage({ id = "CUS-00125" }: { id?: string }) { const customer = customers.find((entry) => entry.id === id) ?? customers[0]!; return <div className="space-y-6"><PageHeader eyebrow={`${customer.id} · ${customer.phone}`} title={customer.name} description={`${customer.location} · Customer since August 2026`} actions={<><Button variant="outline" asChild><EditLink basePath="/customers" id={customer.id}><Pencil/> Edit</EditLink></Button><Button variant="outline" asChild><Link to="/enquiries/new">New Enquiry</Link></Button><Button asChild><Link to="/bookings/new">New Booking</Link></Button></>}/><GlassCard className="p-6"><JourneyStepper active={6}/></GlassCard><div className="grid gap-5 lg:grid-cols-[0.75fr_1.25fr]"><GlassCard className="p-6"><h2 className="font-display text-lg font-bold">Customer information</h2><dl className="mt-5 space-y-4">{[["Phone", "9876543210"], ["Email", "ravi.kumar@gmail.com"], ["Address", "18, Taramani Link Road, Velachery, Chennai – 600042"], ["Date of birth", "14 March 1991"], ["ID", "Aadhaar · XXXX 4821"]].map(([label, value]) => <div key={label}><dt className="text-xs font-semibold uppercase text-muted-foreground">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>)}</dl></GlassCard><GlassCard className="p-6"><Tabs defaultValue="bookings"><TabsList className="max-w-full justify-start overflow-x-auto"><TabsTrigger value="bookings">Bookings</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger><TabsTrigger value="finance">Finance</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList><TabsContent value="bookings" className="mt-5"><div className="rounded-xl border border-border p-4"><div className="flex items-center justify-between"><div><Link to="/bookings/$id" params={{ id: "BK-2026-00125" }} className="font-semibold text-primary">BK-2026-00125</Link><p className="text-sm text-muted-foreground">TVS Jupiter ZX · Starlight Blue</p></div><StatusBadge status="Registration Pending"/></div></div></TabsContent><TabsContent value="payments" className="mt-5 text-sm text-muted-foreground">Booking advance of ₹30,450 received by UPI.</TabsContent><TabsContent value="finance" className="mt-5 text-sm text-muted-foreground">TVS Credit application approved for ₹78,000.</TabsContent><TabsContent value="documents" className="mt-5 text-sm text-muted-foreground">Aadhaar, PAN and address proof verified.</TabsContent></Tabs></GlassCard></div></div>; }

const moduleConfig = {
  enquiries: ["Enquiries", "Track customer interest and follow-ups.", "New Enquiry", "/enquiries/new"],
  proforma: ["Proforma Invoices", "Prepare transparent on-road quotations without re-entering customer data.", "New Proforma", "/proforma/new"],
  bookings: ["Bookings", "Track every sale from advance payment to delivery.", "New Booking", "/bookings/new"],
  finance: ["Finance Applications", "Monitor NBFC applications, documents, approvals, and disbursals.", "New Application", "/finance/applications/new"],
  insurance: ["Insurance", "Track policy requests, issuance, and upcoming expiry dates.", "New Insurance", "/insurance/new"],
  registration: ["Registration", "Manage RTO applications through number allocation and completion.", "New Registration", "/registration/new"],
  refinance: ["Refinance", "Move existing vehicle loans to better partners.", "New Refinance", "/finance/refinance/new"],
  deliveries: ["Deliveries", "Complete every handover only after all prerequisites are ready.", "Schedule Delivery", "/deliveries/new"],
} as const;
export function ListPage({ type }: { type: keyof typeof moduleConfig }) { const [title, description, action, to] = moduleConfig[type]; const [status, setStatus] = useState("All"); const rows = useMemo(() => (status === "All" ? records[type] : (records[type] ?? []).filter((row) => row.status === status)), [status, type]); return <div className="space-y-6"><PageHeader title={title} description={description} actions={<Button asChild><Link to={to}><Plus/> {action}</Link></Button>}/>{type === "finance" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KpiCard label="Applications" value="24" trend="This month" icon={<FileText/>}/><KpiCard label="Pending" value="5" trend="2 urgent" icon={<Clock3/>}/><KpiCard label="Approved" value="14" trend="+8%" icon={<Check/>}/><KpiCard label="Rejected" value="2" trend="8.3%" icon={<ClipboardCheck/>}/><KpiCard label="Disbursed" value="₹8.4L" trend="This month" icon={<IndianRupee/>}/></div>}<FilterPills options={[...pageFilters[type]]} active={status} onChange={setStatus}/><ModernTable rows={rows} basePath={type === "finance" ? "/finance/applications" : `/${type}`}/></div>; }

const basePathFor: Record<keyof typeof moduleConfig, string> = { enquiries: "/enquiries", proforma: "/proforma", bookings: "/bookings", finance: "/finance/applications", refinance: "/finance/refinance", insurance: "/insurance", registration: "/registration", deliveries: "/deliveries" };

export function DetailPage({ type, id }: { type: keyof typeof moduleConfig; id: string }) { const row = records[type].find((entry) => entry.id === id) ?? records[type][0]; if (!row) return null; const isBooking = type === "bookings"; return <div className="space-y-6"><PageHeader eyebrow={row.id} title={row.primary} description={row.secondary} actions={<><Button variant="outline" asChild><EditLink basePath={basePathFor[type]} id={row.id}><Pencil/> Edit</EditLink></Button><Button variant="outline" onClick={() => window.print()}><Printer/> Print</Button><Button variant="outline" onClick={() => toast.success("Download started")}><Download/> Download</Button></>}/>{isBooking && <GlassCard className="p-6"><JourneyStepper active={6}/></GlassCard>}<div className="grid gap-5 lg:grid-cols-[1.4fr_0.6fr]"><div className="grid gap-5 sm:grid-cols-2">{["Customer", "Vehicle", "Payment", "Finance", "Insurance", "Registration", "Documents"].map((title, index) => <GlassCard key={title} className="p-5"><div className="flex items-center justify-between"><h2 className="font-display font-bold">{title}</h2><StatusBadge status={index < 5 ? "Completed" : index === 5 ? "Processing" : "3 files"}/></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{index === 0 ? `${row.primary} · 9876543210 · Chennai` : index === 1 ? row.secondary : index === 2 ? `${formatCurrency(row.amount ?? 108450)} · UPI + Finance` : "Information carried forward automatically from the previous stage."}</p></GlassCard>)}</div><aside className="space-y-4"><GlassCard className="border-primary/20 bg-primary p-6 text-primary-foreground"><p className="text-xs font-bold uppercase opacity-75">Current stage</p><h2 className="mt-2 text-2xl font-bold">{row.status}</h2><div className="my-5 h-px bg-primary-foreground/20"/><p className="text-xs font-bold uppercase opacity-75">Next action</p><p className="mt-2 font-semibold">Upload registration confirmation</p><Button variant="secondary" className="mt-5 w-full" onClick={() => toast.success(`${type} updated successfully`)}>Update status</Button></GlassCard><GlassCard className="p-5"><h3 className="font-bold">Activity timeline</h3>{["Record created", "Documents verified", "Application updated", "Awaiting next action"].map((item, index) => <div key={item} className="mt-4 flex gap-3"><span className="mt-1 size-2 rounded-full bg-primary"/><div><p className="text-sm font-medium">{item}</p><p className="text-xs text-muted-foreground">{index + 1} day ago · Priya S</p></div></div>)}</GlassCard></aside></div></div>; }

export function InventoryPage() { const [view, setView] = useState("table"); const [stock, setStock] = useState("All"); const list = useMemo(() => (stock === "All" ? vehicles : vehicles.filter((vehicle) => vehicle.status === stock)), [stock]); return <div className="space-y-6"><PageHeader title="Vehicle Inventory" description="38 vehicles available across the showroom and transit stock." actions={<><Button variant="outline"><Upload/> Import</Button><Button asChild><Link to="/inventory/new"><Plus/> Add Vehicle</Link></Button></>}/><div className="flex justify-between gap-3"><FilterPills options={[...pageFilters.inventory]} active={stock} onChange={setStock}/><div className="flex rounded-xl border border-border bg-card p-1"><Button size="sm" variant={view === "table" ? "default" : "ghost"} onClick={() => setView("table")}>Table</Button><Button size="sm" variant={view === "card" ? "default" : "ghost"} onClick={() => setView("card")}>Cards</Button></div></div>{view === "card" ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map((vehicle) => <Link key={vehicle.id} to="/inventory/$id" params={{ id: vehicle.id }}><GlassCard className="p-5 transition hover:-translate-y-0.5 hover:shadow-float"><div className="flex justify-between"><Bike className="text-primary"/><StatusBadge status={vehicle.status}/></div><h2 className="mt-8 font-display text-xl font-bold">{vehicle.model}</h2><p className="text-sm text-muted-foreground">{vehicle.variant} · {vehicle.colour}</p><p className="mt-4 text-lg font-bold">{formatCurrency(vehicle.sellingPrice)}</p><p className="mt-1 text-xs text-muted-foreground">{vehicle.chassis}</p></GlassCard></Link>)}</div> : <GlassCard className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead className="bg-muted/60 text-left text-xs uppercase text-muted-foreground"><tr>{["Vehicle", "Vehicle ID", "Chassis", "Colour", "Selling Price", "Status"].map((head) => <th key={head} className="px-5 py-3.5">{head}</th>)}</tr></thead><tbody>{list.map((vehicle) => <tr key={vehicle.id} className="border-t border-border/60"><td className="px-5 py-4"><Link to="/inventory/$id" params={{ id: vehicle.id }} className="font-semibold text-primary">{vehicle.model}</Link><p className="text-xs text-muted-foreground">{vehicle.variant}</p></td><td className="px-5 py-4 text-sm">{vehicle.id}</td><td className="px-5 py-4 text-sm text-muted-foreground">{vehicle.chassis}</td><td className="px-5 py-4 text-sm">{vehicle.colour}</td><td className="px-5 py-4 font-semibold">{formatCurrency(vehicle.sellingPrice)}</td><td className="px-5 py-4"><StatusBadge status={vehicle.status}/></td></tr>)}</tbody></table></GlassCard>}</div>; }

export function VehicleDetailPage({ id }: { id: string }) { const vehicle = vehicles.find((v) => v.id === id) ?? vehicles[0]; if (!vehicle) return null; return <div className="space-y-6"><PageHeader eyebrow={vehicle.id} title={vehicle.model} description={`${vehicle.variant} · ${vehicle.colour}`} actions={<><StatusBadge status={vehicle.status}/><Button variant="outline" asChild><EditLink basePath="/inventory" id={vehicle.id}><Pencil/> Edit</EditLink></Button></>}/><div className="grid gap-5 lg:grid-cols-[1fr_0.7fr]"><GlassCard className="p-6"><h2 className="font-display text-lg font-bold">Vehicle information</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Chassis number", vehicle.chassis], ["Engine number", vehicle.engine], ["Model", vehicle.model], ["Variant", vehicle.variant], ["Purchase price", formatCurrency(vehicle.purchasePrice)], ["Selling price", formatCurrency(vehicle.sellingPrice)]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl></GlassCard><GlassCard className="p-6"><h2 className="font-display text-lg font-bold">Vehicle history</h2>{["Stock received", "Quality inspection completed", "Reserved for customer", "Booking linked"].map((item, index) => <div key={item} className="mt-5 flex gap-3"><span className="grid size-7 place-items-center rounded-full bg-primary-soft text-xs font-bold text-primary">{index + 1}</span><div><p className="text-sm font-semibold">{item}</p><p className="text-xs text-muted-foreground">{12 - index} Sep 2026 · Kannan</p></div></div>)}</GlassCard></div></div>; }

export function RefinancePage() { const [refStatus, setRefStatus] = useState("All"); const refRows = useMemo(() => (refStatus === "All" ? records.refinance : (records.refinance ?? []).filter((row) => row.status === refStatus)), [refStatus]); return <div className="space-y-6"><PageHeader title="Refinance" description="Manage existing vehicle finance and new partner applications." actions={<Button asChild><Link to="/finance/refinance/new"><Plus/> New Refinance</Link></Button>}/><FilterPills options={[...pageFilters.refinance]} active={refStatus} onChange={setRefStatus}/><ModernTable rows={refRows} basePath="/finance/refinance"/></div>; }

export function DeliveriesPage() { return <div className="space-y-6"><PageHeader title="Today's Deliveries" description="4 scheduled handovers · readiness updates automatically from connected stages." actions={<Button asChild><Link to="/deliveries/new"><Plus/> Schedule Delivery</Link></Button>}/><div className="grid gap-5 lg:grid-cols-2">{records.deliveries.map((row, index) => <GlassCard key={row.id} className="p-6"><div className="flex items-start justify-between"><div><h2 className="font-display text-xl font-bold">{row.primary}</h2><p className="text-sm text-muted-foreground">{row.secondary}</p><p className="mt-1 text-xs text-primary">{row.detail}</p></div><div className="flex items-center gap-2"><StatusBadge status={row.status}/><Button variant="ghost" size="icon" asChild><EditLink basePath="/deliveries" id={row.id}><Pencil className="size-4"/></EditLink></Button></div></div><div className="my-5 grid grid-cols-2 gap-2">{["Payment", "Finance", "Insurance", "Registration"].map((item, i) => <div key={item} className="flex items-center gap-2 rounded-lg bg-muted/70 p-2 text-xs font-semibold"><span className={i === 3 && index === 1 ? "text-warning" : "text-success"}>{i === 3 && index === 1 ? "!" : "✓"}</span>{item}</div>)}</div>{index === 1 ? <div className="rounded-xl bg-warning-soft p-3 text-sm font-semibold text-warning">Registration pending. Delivery cannot be completed.</div> : <Button className="w-full" asChild><Link to="/deliveries/$id" params={{ id: row.id }}>Complete Delivery</Link></Button>}</GlassCard>)}</div></div>; }

export function DeliveryDetailPage({ id = "DEL-2026-0081" }: { id?: string }) { const [checked, setChecked] = useState([true, true, true, true, false, false, false, false]); const complete = checked.every(Boolean); return <div className="mx-auto max-w-3xl space-y-6"><PageHeader eyebrow={id} title="Delivery Checklist" description="Arun Prakash · TVS Apache RTR 160 · BK-2026-00123"/><GlassCard className="p-6"><div className="space-y-3">{["Payment completed", "Finance completed", "Insurance completed", "Registration completed", "Vehicle inspection", "Accessories fitted", "Documents handed over", "Customer acknowledgement"].map((item, index) => <label key={item} className="flex cursor-pointer items-center gap-3 rounded-xl border border-border p-4 hover:bg-primary-soft"><Checkbox checked={checked[index]} onCheckedChange={(value) => setChecked((items) => items.map((current, i) => i === index ? Boolean(value) : current))}/><span className="font-medium">{item}</span>{checked[index] && <Check className="ml-auto size-4 text-success"/>}</label>)}</div><Dialog><DialogTrigger asChild><Button className="mt-6 w-full" size="lg" disabled={!complete}>Complete Delivery</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Complete this delivery?</DialogTitle><DialogDescription>This will mark the vehicle as delivered and close the customer journey.</DialogDescription></DialogHeader><DialogFooter><Button onClick={() => toast.success("Delivery completed")}>Confirm Delivery</Button></DialogFooter></DialogContent></Dialog></GlassCard></div>; }

export function AccountsPage({ monthly = false }: { monthly?: boolean }) { const totals = monthly ? ["₹24,85,000", "₹3,42,450", "₹21,42,550"] : ["₹1,85,000", "₹23,450", "₹1,61,550"]; return <div className="space-y-6"><PageHeader title={monthly ? "September 2026" : "Accounts"} description={monthly ? "Automatically generated from daily showroom transactions." : "Today's transactions automatically become daily and monthly reports."} actions={<Button asChild><Link to="/accounts/new"><Plus/> New Transaction</Link></Button>}/><div className="grid gap-4 md:grid-cols-3"><KpiCard label="Total Income" value={totals[0]} trend="+12.8%" icon={<TrendingUp/>}/><KpiCard label="Total Expenses" value={totals[1]} trend="Within plan" icon={<WalletCards/>}/><KpiCard label="Net" value={totals[2]} trend="Healthy" icon={<CircleDollarSign/>}/></div><GlassCard className="p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Income vs Expense</h2><StatusBadge status="Auto-updated" tone="success"/></div><Suspense fallback={<div className="h-72 w-full animate-pulse rounded-xl bg-muted/50"/>}><AccountsChart/></Suspense></GlassCard><div className="grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-3 text-center"><div className="rounded-xl bg-card p-4 font-semibold">Today's Transactions</div><ChevronRight className="text-primary"/><div className="rounded-xl bg-primary-soft p-4 font-semibold text-primary">Automatic Daily Summary</div><ChevronRight className="text-primary"/><div className="rounded-xl bg-success-soft p-4 font-semibold text-success">Automatic Monthly Summary</div></div></div>; }

export function ReportsPage() { return <div className="space-y-6"><PageHeader title="Reports" description="Operational and financial intelligence generated from the work your team already completed." actions={<><Button variant="outline"><Printer/> Print</Button><Button variant="outline"><FileSpreadsheet/> Excel</Button><Button><Download/> PDF</Button></>}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Sales", ["Daily sales", "Monthly sales", "Model-wise sales", "Cash vs finance"]], ["Finance", ["Applications", "Approved & rejected", "Disbursed", "NBFC-wise"]], ["Inventory", ["Available", "Booked", "Sold", "Model-wise stock"]], ["Operations", ["Pending insurance", "Pending registration", "Pending delivery", "Follow-ups"]]].map(([title, links]) => <GlassCard key={title as string} className="p-5"><h2 className="font-display text-lg font-bold">{title as string}</h2><div className="mt-4 space-y-1">{(links as string[]).map((link) => <button key={link} onClick={() => toast.success(`${link} report ready`)} className="flex w-full items-center justify-between rounded-lg p-2 text-left text-sm hover:bg-primary-soft hover:text-primary">{link}<ChevronRight className="size-4"/></button>)}</div></GlassCard>)}</div><AccountsPage monthly/></div>; }

export function SettingsPage() { return <div className="space-y-6"><PageHeader title="Settings" description="Configure your showroom, team, partners, and operating preferences."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["Showroom information", "Business name, GST, address and branding", Settings], ["Users", "Team access and account status", Users], ["Roles & permissions", "Control operational access by role", ShieldCheck], ["Vehicle master", "Models, variants and colours", Bike], ["Finance partners", "NBFC contacts and schemes", Landmark], ["Categories & payments", "Expense, income and payment modes", WalletCards]].map(([title, detail, Icon]) => <GlassCard key={title as string} className="p-5"><span className="grid size-10 place-items-center rounded-xl bg-primary-soft text-primary"><Icon/></span><h2 className="mt-5 font-display text-lg font-bold">{title as string}</h2><p className="mt-1 text-sm text-muted-foreground">{detail as string}</p><Button variant="ghost" className="mt-4 px-0 text-primary">Manage <ChevronRight/></Button></GlassCard>)}</div></div>; }