/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as AccountsDailyRouteImport } from './routes/accounts.daily'
import { Route as AccountsMonthlyRouteImport } from './routes/accounts.monthly'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as DeliveriesNewRouteImport } from './routes/deliveries.new'
import { Route as EnquiriesIndexRouteImport } from './routes/enquiries.index'
import { Route as EnquiriesNewRouteImport } from './routes/enquiries.new'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as InsuranceIndexRouteImport } from './routes/insurance.index'
import { Route as InsuranceNewRouteImport } from './routes/insurance.new'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'
import { Route as ProformaIndexRouteImport } from './routes/proforma.index'
import { Route as ProformaNewRouteImport } from './routes/proforma.new'
import { Route as RegistrationIndexRouteImport } from './routes/registration.index'
import { Route as RegistrationNewRouteImport } from './routes/registration.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMasterDataRouteImport } from './routes/settings.master-data'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as BookingsIdIndexRouteImport } from './routes/bookings.$id.index'
import { Route as BookingsIdEditRouteImport } from './routes/bookings.$id.edit'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'
import { Route as DeliveriesIdIndexRouteImport } from './routes/deliveries.$id.index'
import { Route as DeliveriesIdEditRouteImport } from './routes/deliveries.$id.edit'
import { Route as EnquiriesIdIndexRouteImport } from './routes/enquiries.$id.index'
import { Route as EnquiriesIdEditRouteImport } from './routes/enquiries.$id.edit'
import { Route as FinanceApplicationsIndexRouteImport } from './routes/finance.applications.index'
import { Route as FinanceApplicationsNewRouteImport } from './routes/finance.applications.new'
import { Route as FinanceRefinanceIndexRouteImport } from './routes/finance.refinance.index'
import { Route as FinanceRefinanceNewRouteImport } from './routes/finance.refinance.new'
import { Route as InsuranceIdIndexRouteImport } from './routes/insurance.$id.index'
import { Route as InsuranceIdEditRouteImport } from './routes/insurance.$id.edit'
import { Route as InventoryIdIndexRouteImport } from './routes/inventory.$id.index'
import { Route as InventoryIdEditRouteImport } from './routes/inventory.$id.edit'
import { Route as ProformaIdIndexRouteImport } from './routes/proforma.$id.index'
import { Route as ProformaIdEditRouteImport } from './routes/proforma.$id.edit'
import { Route as RegistrationIdIndexRouteImport } from './routes/registration.$id.index'
import { Route as RegistrationIdEditRouteImport } from './routes/registration.$id.edit'
import { Route as FinanceApplicationsIdIndexRouteImport } from './routes/finance.applications.$id.index'
import { Route as FinanceApplicationsIdEditRouteImport } from './routes/finance.applications.$id.edit'
import { Route as FinanceRefinanceIdIndexRouteImport } from './routes/finance.refinance.$id.index'
import { Route as FinanceRefinanceIdEditRouteImport } from './routes/finance.refinance.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsDailyRoute = AccountsDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsMonthlyRoute = AccountsMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesNewRoute = DeliveriesNewRouteImport.update({
  id: '/deliveries/new',
  path: '/deliveries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesIndexRoute = EnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesNewRoute = EnquiriesNewRouteImport.update({
  id: '/enquiries/new',
  path: '/enquiries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/insurance/',
  path: '/insurance/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceNewRoute = InsuranceNewRouteImport.update({
  id: '/insurance/new',
  path: '/insurance/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaIndexRoute = ProformaIndexRouteImport.update({
  id: '/proforma/',
  path: '/proforma/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaNewRoute = ProformaNewRouteImport.update({
  id: '/proforma/new',
  path: '/proforma/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationNewRoute = RegistrationNewRouteImport.update({
  id: '/registration/new',
  path: '/registration/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMasterDataRoute = SettingsMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const BookingsIdIndexRoute = BookingsIdIndexRouteImport.update({
  id: '/bookings/$id/',
  path: '/bookings/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdEditRoute = BookingsIdEditRouteImport.update({
  id: '/bookings/$id/edit',
  path: '/bookings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIdIndexRoute = DeliveriesIdIndexRouteImport.update({
  id: '/deliveries/$id/',
  path: '/deliveries/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesIdEditRoute = DeliveriesIdEditRouteImport.update({
  id: '/deliveries/$id/edit',
  path: '/deliveries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesIdIndexRoute = EnquiriesIdIndexRouteImport.update({
  id: '/enquiries/$id/',
  path: '/enquiries/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesIdEditRoute = EnquiriesIdEditRouteImport.update({
  id: '/enquiries/$id/edit',
  path: '/enquiries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApplicationsIndexRoute =
  FinanceApplicationsIndexRouteImport.update({
    id: '/finance/applications/',
    path: '/finance/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceApplicationsNewRoute = FinanceApplicationsNewRouteImport.update({
  id: '/finance/applications/new',
  path: '/finance/applications/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRefinanceIndexRoute = FinanceRefinanceIndexRouteImport.update({
  id: '/finance/refinance/',
  path: '/finance/refinance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRefinanceNewRoute = FinanceRefinanceNewRouteImport.update({
  id: '/finance/refinance/new',
  path: '/finance/refinance/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIdIndexRoute = InsuranceIdIndexRouteImport.update({
  id: '/insurance/$id/',
  path: '/insurance/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIdEditRoute = InsuranceIdEditRouteImport.update({
  id: '/insurance/$id/edit',
  path: '/insurance/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdIndexRoute = InventoryIdIndexRouteImport.update({
  id: '/inventory/$id/',
  path: '/inventory/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIdEditRoute = InventoryIdEditRouteImport.update({
  id: '/inventory/$id/edit',
  path: '/inventory/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaIdIndexRoute = ProformaIdIndexRouteImport.update({
  id: '/proforma/$id/',
  path: '/proforma/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProformaIdEditRoute = ProformaIdEditRouteImport.update({
  id: '/proforma/$id/edit',
  path: '/proforma/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIdIndexRoute = RegistrationIdIndexRouteImport.update({
  id: '/registration/$id/',
  path: '/registration/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIdEditRoute = RegistrationIdEditRouteImport.update({
  id: '/registration/$id/edit',
  path: '/registration/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApplicationsIdIndexRoute =
  FinanceApplicationsIdIndexRouteImport.update({
    id: '/finance/applications/$id/',
    path: '/finance/applications/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceApplicationsIdEditRoute =
  FinanceApplicationsIdEditRouteImport.update({
    id: '/finance/applications/$id/edit',
    path: '/finance/applications/$id/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceRefinanceIdIndexRoute = FinanceRefinanceIdIndexRouteImport.update({
  id: '/finance/refinance/$id/',
  path: '/finance/refinance/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRefinanceIdEditRoute = FinanceRefinanceIdEditRouteImport.update({
  id: '/finance/refinance/$id/edit',
  path: '/finance/refinance/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/accounts/daily': typeof AccountsDailyRoute
  '/accounts/monthly': typeof AccountsMonthlyRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bookings/new': typeof BookingsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/enquiries/new': typeof EnquiriesNewRoute
  '/insurance/new': typeof InsuranceNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/proforma/new': typeof ProformaNewRoute
  '/registration/new': typeof RegistrationNewRoute
  '/settings/master-data': typeof SettingsMasterDataRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/enquiries/': typeof EnquiriesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/proforma/': typeof ProformaIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/enquiries/$id/edit': typeof EnquiriesIdEditRoute
  '/finance/applications/new': typeof FinanceApplicationsNewRoute
  '/finance/refinance/new': typeof FinanceRefinanceNewRoute
  '/insurance/$id/edit': typeof InsuranceIdEditRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/proforma/$id/edit': typeof ProformaIdEditRoute
  '/registration/$id/edit': typeof RegistrationIdEditRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
  '/deliveries/$id/': typeof DeliveriesIdIndexRoute
  '/enquiries/$id/': typeof EnquiriesIdIndexRoute
  '/finance/applications/': typeof FinanceApplicationsIndexRoute
  '/finance/refinance/': typeof FinanceRefinanceIndexRoute
  '/insurance/$id/': typeof InsuranceIdIndexRoute
  '/inventory/$id/': typeof InventoryIdIndexRoute
  '/proforma/$id/': typeof ProformaIdIndexRoute
  '/registration/$id/': typeof RegistrationIdIndexRoute
  '/finance/applications/$id/edit': typeof FinanceApplicationsIdEditRoute
  '/finance/refinance/$id/edit': typeof FinanceRefinanceIdEditRoute
  '/finance/applications/$id/': typeof FinanceApplicationsIdIndexRoute
  '/finance/refinance/$id/': typeof FinanceRefinanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/accounts/daily': typeof AccountsDailyRoute
  '/accounts/monthly': typeof AccountsMonthlyRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bookings/new': typeof BookingsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/enquiries/new': typeof EnquiriesNewRoute
  '/insurance/new': typeof InsuranceNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/proforma/new': typeof ProformaNewRoute
  '/registration/new': typeof RegistrationNewRoute
  '/settings/master-data': typeof SettingsMasterDataRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts': typeof AccountsIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/enquiries': typeof EnquiriesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/insurance': typeof InsuranceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/proforma': typeof ProformaIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/enquiries/$id/edit': typeof EnquiriesIdEditRoute
  '/finance/applications/new': typeof FinanceApplicationsNewRoute
  '/finance/refinance/new': typeof FinanceRefinanceNewRoute
  '/insurance/$id/edit': typeof InsuranceIdEditRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/proforma/$id/edit': typeof ProformaIdEditRoute
  '/registration/$id/edit': typeof RegistrationIdEditRoute
  '/bookings/$id': typeof BookingsIdIndexRoute
  '/customers/$id': typeof CustomersIdIndexRoute
  '/deliveries/$id': typeof DeliveriesIdIndexRoute
  '/enquiries/$id': typeof EnquiriesIdIndexRoute
  '/finance/applications': typeof FinanceApplicationsIndexRoute
  '/finance/refinance': typeof FinanceRefinanceIndexRoute
  '/insurance/$id': typeof InsuranceIdIndexRoute
  '/inventory/$id': typeof InventoryIdIndexRoute
  '/proforma/$id': typeof ProformaIdIndexRoute
  '/registration/$id': typeof RegistrationIdIndexRoute
  '/finance/applications/$id/edit': typeof FinanceApplicationsIdEditRoute
  '/finance/refinance/$id/edit': typeof FinanceRefinanceIdEditRoute
  '/finance/applications/$id': typeof FinanceApplicationsIdIndexRoute
  '/finance/refinance/$id': typeof FinanceRefinanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/accounts/daily': typeof AccountsDailyRoute
  '/accounts/monthly': typeof AccountsMonthlyRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bookings/new': typeof BookingsNewRoute
  '/customers/new': typeof CustomersNewRoute
  '/deliveries/new': typeof DeliveriesNewRoute
  '/enquiries/new': typeof EnquiriesNewRoute
  '/insurance/new': typeof InsuranceNewRoute
  '/inventory/new': typeof InventoryNewRoute
  '/proforma/new': typeof ProformaNewRoute
  '/registration/new': typeof RegistrationNewRoute
  '/settings/master-data': typeof SettingsMasterDataRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/accounts/': typeof AccountsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/enquiries/': typeof EnquiriesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/proforma/': typeof ProformaIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/deliveries/$id/edit': typeof DeliveriesIdEditRoute
  '/enquiries/$id/edit': typeof EnquiriesIdEditRoute
  '/finance/applications/new': typeof FinanceApplicationsNewRoute
  '/finance/refinance/new': typeof FinanceRefinanceNewRoute
  '/insurance/$id/edit': typeof InsuranceIdEditRoute
  '/inventory/$id/edit': typeof InventoryIdEditRoute
  '/proforma/$id/edit': typeof ProformaIdEditRoute
  '/registration/$id/edit': typeof RegistrationIdEditRoute
  '/bookings/$id/': typeof BookingsIdIndexRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
  '/deliveries/$id/': typeof DeliveriesIdIndexRoute
  '/enquiries/$id/': typeof EnquiriesIdIndexRoute
  '/finance/applications/': typeof FinanceApplicationsIndexRoute
  '/finance/refinance/': typeof FinanceRefinanceIndexRoute
  '/insurance/$id/': typeof InsuranceIdIndexRoute
  '/inventory/$id/': typeof InventoryIdIndexRoute
  '/proforma/$id/': typeof ProformaIdIndexRoute
  '/registration/$id/': typeof RegistrationIdIndexRoute
  '/finance/applications/$id/edit': typeof FinanceApplicationsIdEditRoute
  '/finance/refinance/$id/edit': typeof FinanceRefinanceIdEditRoute
  '/finance/applications/$id/': typeof FinanceApplicationsIdIndexRoute
  '/finance/refinance/$id/': typeof FinanceRefinanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/accounts/daily'
    | '/accounts/monthly'
    | '/accounts/new'
    | '/bookings/new'
    | '/customers/new'
    | '/deliveries/new'
    | '/enquiries/new'
    | '/insurance/new'
    | '/inventory/new'
    | '/proforma/new'
    | '/registration/new'
    | '/settings/master-data'
    | '/settings/roles'
    | '/settings/users'
    | '/accounts/'
    | '/bookings/'
    | '/customers/'
    | '/deliveries/'
    | '/enquiries/'
    | '/finance/'
    | '/insurance/'
    | '/inventory/'
    | '/proforma/'
    | '/registration/'
    | '/settings/'
    | '/bookings/$id/edit'
    | '/customers/$id/edit'
    | '/deliveries/$id/edit'
    | '/enquiries/$id/edit'
    | '/finance/applications/new'
    | '/finance/refinance/new'
    | '/insurance/$id/edit'
    | '/inventory/$id/edit'
    | '/proforma/$id/edit'
    | '/registration/$id/edit'
    | '/bookings/$id/'
    | '/customers/$id/'
    | '/deliveries/$id/'
    | '/enquiries/$id/'
    | '/finance/applications/'
    | '/finance/refinance/'
    | '/insurance/$id/'
    | '/inventory/$id/'
    | '/proforma/$id/'
    | '/registration/$id/'
    | '/finance/applications/$id/edit'
    | '/finance/refinance/$id/edit'
    | '/finance/applications/$id/'
    | '/finance/refinance/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reports'
    | '/accounts/daily'
    | '/accounts/monthly'
    | '/accounts/new'
    | '/bookings/new'
    | '/customers/new'
    | '/deliveries/new'
    | '/enquiries/new'
    | '/insurance/new'
    | '/inventory/new'
    | '/proforma/new'
    | '/registration/new'
    | '/settings/master-data'
    | '/settings/roles'
    | '/settings/users'
    | '/accounts'
    | '/bookings'
    | '/customers'
    | '/deliveries'
    | '/enquiries'
    | '/finance'
    | '/insurance'
    | '/inventory'
    | '/proforma'
    | '/registration'
    | '/settings'
    | '/bookings/$id/edit'
    | '/customers/$id/edit'
    | '/deliveries/$id/edit'
    | '/enquiries/$id/edit'
    | '/finance/applications/new'
    | '/finance/refinance/new'
    | '/insurance/$id/edit'
    | '/inventory/$id/edit'
    | '/proforma/$id/edit'
    | '/registration/$id/edit'
    | '/bookings/$id'
    | '/customers/$id'
    | '/deliveries/$id'
    | '/enquiries/$id'
    | '/finance/applications'
    | '/finance/refinance'
    | '/insurance/$id'
    | '/inventory/$id'
    | '/proforma/$id'
    | '/registration/$id'
    | '/finance/applications/$id/edit'
    | '/finance/refinance/$id/edit'
    | '/finance/applications/$id'
    | '/finance/refinance/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/reports'
    | '/accounts/daily'
    | '/accounts/monthly'
    | '/accounts/new'
    | '/bookings/new'
    | '/customers/new'
    | '/deliveries/new'
    | '/enquiries/new'
    | '/insurance/new'
    | '/inventory/new'
    | '/proforma/new'
    | '/registration/new'
    | '/settings/master-data'
    | '/settings/roles'
    | '/settings/users'
    | '/accounts/'
    | '/bookings/'
    | '/customers/'
    | '/deliveries/'
    | '/enquiries/'
    | '/finance/'
    | '/insurance/'
    | '/inventory/'
    | '/proforma/'
    | '/registration/'
    | '/settings/'
    | '/bookings/$id/edit'
    | '/customers/$id/edit'
    | '/deliveries/$id/edit'
    | '/enquiries/$id/edit'
    | '/finance/applications/new'
    | '/finance/refinance/new'
    | '/insurance/$id/edit'
    | '/inventory/$id/edit'
    | '/proforma/$id/edit'
    | '/registration/$id/edit'
    | '/bookings/$id/'
    | '/customers/$id/'
    | '/deliveries/$id/'
    | '/enquiries/$id/'
    | '/finance/applications/'
    | '/finance/refinance/'
    | '/insurance/$id/'
    | '/inventory/$id/'
    | '/proforma/$id/'
    | '/registration/$id/'
    | '/finance/applications/$id/edit'
    | '/finance/refinance/$id/edit'
    | '/finance/applications/$id/'
    | '/finance/refinance/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ReportsRoute: typeof ReportsRoute
  AccountsNewRoute: typeof AccountsNewRoute
  BookingsNewRoute: typeof BookingsNewRoute
  CustomersNewRoute: typeof CustomersNewRoute
  DeliveriesNewRoute: typeof DeliveriesNewRoute
  EnquiriesNewRoute: typeof EnquiriesNewRoute
  InsuranceNewRoute: typeof InsuranceNewRoute
  InventoryNewRoute: typeof InventoryNewRoute
  ProformaNewRoute: typeof ProformaNewRoute
  RegistrationNewRoute: typeof RegistrationNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
  EnquiriesIndexRoute: typeof EnquiriesIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProformaIndexRoute: typeof ProformaIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  BookingsIdEditRoute: typeof BookingsIdEditRoute
  CustomersIdEditRoute: typeof CustomersIdEditRoute
  DeliveriesIdEditRoute: typeof DeliveriesIdEditRoute
  EnquiriesIdEditRoute: typeof EnquiriesIdEditRoute
  FinanceApplicationsNewRoute: typeof FinanceApplicationsNewRoute
  FinanceRefinanceNewRoute: typeof FinanceRefinanceNewRoute
  InsuranceIdEditRoute: typeof InsuranceIdEditRoute
  InventoryIdEditRoute: typeof InventoryIdEditRoute
  ProformaIdEditRoute: typeof ProformaIdEditRoute
  RegistrationIdEditRoute: typeof RegistrationIdEditRoute
  BookingsIdIndexRoute: typeof BookingsIdIndexRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
  DeliveriesIdIndexRoute: typeof DeliveriesIdIndexRoute
  EnquiriesIdIndexRoute: typeof EnquiriesIdIndexRoute
  FinanceApplicationsIndexRoute: typeof FinanceApplicationsIndexRoute
  FinanceRefinanceIndexRoute: typeof FinanceRefinanceIndexRoute
  InsuranceIdIndexRoute: typeof InsuranceIdIndexRoute
  InventoryIdIndexRoute: typeof InventoryIdIndexRoute
  ProformaIdIndexRoute: typeof ProformaIdIndexRoute
  RegistrationIdIndexRoute: typeof RegistrationIdIndexRoute
  FinanceApplicationsIdEditRoute: typeof FinanceApplicationsIdEditRoute
  FinanceRefinanceIdEditRoute: typeof FinanceRefinanceIdEditRoute
  FinanceApplicationsIdIndexRoute: typeof FinanceApplicationsIdIndexRoute
  FinanceRefinanceIdIndexRoute: typeof FinanceRefinanceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/daily': {
      id: '/accounts/daily'
      path: '/daily'
      fullPath: '/accounts/daily'
      preLoaderRoute: typeof AccountsDailyRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/monthly': {
      id: '/accounts/monthly'
      path: '/monthly'
      fullPath: '/accounts/monthly'
      preLoaderRoute: typeof AccountsMonthlyRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/new': {
      id: '/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/deliveries/new'
      preLoaderRoute: typeof DeliveriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/': {
      id: '/enquiries/'
      path: '/enquiries'
      fullPath: '/enquiries/'
      preLoaderRoute: typeof EnquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/new': {
      id: '/enquiries/new'
      path: '/enquiries/new'
      fullPath: '/enquiries/new'
      preLoaderRoute: typeof EnquiriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/new': {
      id: '/insurance/new'
      path: '/insurance/new'
      fullPath: '/insurance/new'
      preLoaderRoute: typeof InsuranceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma/': {
      id: '/proforma/'
      path: '/proforma'
      fullPath: '/proforma/'
      preLoaderRoute: typeof ProformaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma/new': {
      id: '/proforma/new'
      path: '/proforma/new'
      fullPath: '/proforma/new'
      preLoaderRoute: typeof ProformaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration/'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/new': {
      id: '/registration/new'
      path: '/registration/new'
      fullPath: '/registration/new'
      preLoaderRoute: typeof RegistrationNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/master-data': {
      id: '/settings/master-data'
      path: '/master-data'
      fullPath: '/settings/master-data'
      preLoaderRoute: typeof SettingsMasterDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/bookings/$id/': {
      id: '/bookings/$id/'
      path: '/bookings/$id'
      fullPath: '/bookings/$id/'
      preLoaderRoute: typeof BookingsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/edit': {
      id: '/bookings/$id/edit'
      path: '/bookings/$id/edit'
      fullPath: '/bookings/$id/edit'
      preLoaderRoute: typeof BookingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/$id/': {
      id: '/deliveries/$id/'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id/'
      preLoaderRoute: typeof DeliveriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/$id/edit': {
      id: '/deliveries/$id/edit'
      path: '/deliveries/$id/edit'
      fullPath: '/deliveries/$id/edit'
      preLoaderRoute: typeof DeliveriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/$id/': {
      id: '/enquiries/$id/'
      path: '/enquiries/$id'
      fullPath: '/enquiries/$id/'
      preLoaderRoute: typeof EnquiriesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries/$id/edit': {
      id: '/enquiries/$id/edit'
      path: '/enquiries/$id/edit'
      fullPath: '/enquiries/$id/edit'
      preLoaderRoute: typeof EnquiriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/applications/': {
      id: '/finance/applications/'
      path: '/finance/applications'
      fullPath: '/finance/applications/'
      preLoaderRoute: typeof FinanceApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/applications/new': {
      id: '/finance/applications/new'
      path: '/finance/applications/new'
      fullPath: '/finance/applications/new'
      preLoaderRoute: typeof FinanceApplicationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/refinance/': {
      id: '/finance/refinance/'
      path: '/finance/refinance'
      fullPath: '/finance/refinance/'
      preLoaderRoute: typeof FinanceRefinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/refinance/new': {
      id: '/finance/refinance/new'
      path: '/finance/refinance/new'
      fullPath: '/finance/refinance/new'
      preLoaderRoute: typeof FinanceRefinanceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/$id/': {
      id: '/insurance/$id/'
      path: '/insurance/$id'
      fullPath: '/insurance/$id/'
      preLoaderRoute: typeof InsuranceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/$id/edit': {
      id: '/insurance/$id/edit'
      path: '/insurance/$id/edit'
      fullPath: '/insurance/$id/edit'
      preLoaderRoute: typeof InsuranceIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id/': {
      id: '/inventory/$id/'
      path: '/inventory/$id'
      fullPath: '/inventory/$id/'
      preLoaderRoute: typeof InventoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$id/edit': {
      id: '/inventory/$id/edit'
      path: '/inventory/$id/edit'
      fullPath: '/inventory/$id/edit'
      preLoaderRoute: typeof InventoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma/$id/': {
      id: '/proforma/$id/'
      path: '/proforma/$id'
      fullPath: '/proforma/$id/'
      preLoaderRoute: typeof ProformaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proforma/$id/edit': {
      id: '/proforma/$id/edit'
      path: '/proforma/$id/edit'
      fullPath: '/proforma/$id/edit'
      preLoaderRoute: typeof ProformaIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/$id/': {
      id: '/registration/$id/'
      path: '/registration/$id'
      fullPath: '/registration/$id/'
      preLoaderRoute: typeof RegistrationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/$id/edit': {
      id: '/registration/$id/edit'
      path: '/registration/$id/edit'
      fullPath: '/registration/$id/edit'
      preLoaderRoute: typeof RegistrationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/applications/$id/': {
      id: '/finance/applications/$id/'
      path: '/finance/applications/$id'
      fullPath: '/finance/applications/$id/'
      preLoaderRoute: typeof FinanceApplicationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/applications/$id/edit': {
      id: '/finance/applications/$id/edit'
      path: '/finance/applications/$id/edit'
      fullPath: '/finance/applications/$id/edit'
      preLoaderRoute: typeof FinanceApplicationsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/refinance/$id/': {
      id: '/finance/refinance/$id/'
      path: '/finance/refinance/$id'
      fullPath: '/finance/refinance/$id/'
      preLoaderRoute: typeof FinanceRefinanceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/refinance/$id/edit': {
      id: '/finance/refinance/$id/edit'
      path: '/finance/refinance/$id/edit'
      fullPath: '/finance/refinance/$id/edit'
      preLoaderRoute: typeof FinanceRefinanceIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ReportsRoute: ReportsRoute,
  AccountsNewRoute: AccountsNewRoute,
  BookingsNewRoute: BookingsNewRoute,
  CustomersNewRoute: CustomersNewRoute,
  DeliveriesNewRoute: DeliveriesNewRoute,
  EnquiriesNewRoute: EnquiriesNewRoute,
  InsuranceNewRoute: InsuranceNewRoute,
  InventoryNewRoute: InventoryNewRoute,
  ProformaNewRoute: ProformaNewRoute,
  RegistrationNewRoute: RegistrationNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
  EnquiriesIndexRoute: EnquiriesIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProformaIndexRoute: ProformaIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  BookingsIdEditRoute: BookingsIdEditRoute,
  CustomersIdEditRoute: CustomersIdEditRoute,
  DeliveriesIdEditRoute: DeliveriesIdEditRoute,
  EnquiriesIdEditRoute: EnquiriesIdEditRoute,
  FinanceApplicationsNewRoute: FinanceApplicationsNewRoute,
  FinanceRefinanceNewRoute: FinanceRefinanceNewRoute,
  InsuranceIdEditRoute: InsuranceIdEditRoute,
  InventoryIdEditRoute: InventoryIdEditRoute,
  ProformaIdEditRoute: ProformaIdEditRoute,
  RegistrationIdEditRoute: RegistrationIdEditRoute,
  BookingsIdIndexRoute: BookingsIdIndexRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
  DeliveriesIdIndexRoute: DeliveriesIdIndexRoute,
  EnquiriesIdIndexRoute: EnquiriesIdIndexRoute,
  FinanceApplicationsIndexRoute: FinanceApplicationsIndexRoute,
  FinanceRefinanceIndexRoute: FinanceRefinanceIndexRoute,
  InsuranceIdIndexRoute: InsuranceIdIndexRoute,
  InventoryIdIndexRoute: InventoryIdIndexRoute,
  ProformaIdIndexRoute: ProformaIdIndexRoute,
  RegistrationIdIndexRoute: RegistrationIdIndexRoute,
  FinanceApplicationsIdEditRoute: FinanceApplicationsIdEditRoute,
  FinanceRefinanceIdEditRoute: FinanceRefinanceIdEditRoute,
  FinanceApplicationsIdIndexRoute: FinanceApplicationsIdIndexRoute,
  FinanceRefinanceIdIndexRoute: FinanceRefinanceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
